### PR TITLE
Example: Use QueueConfig instead of TopicConfig

### LINKED ISSUE #775: Can't use setBucketNotification with minio server
Hi, I can't find a wait to use setBucketNotification with minio server and amqp notifications.

I have a minio server with amqp notification enabled and I can set notification from mc client with:
```
mc event add  myminio/mybucket arn:minio:sqs::1:amqp --prefix myprefix/
```

But when I try to set notifications from the minio-js client it returns this error:
```
S3Error: MinIO server does not support Topic or Cloud Function based notifications.
```

I'm unable to reproduce this example with a minio server : https://github.com/minio/minio-js/blob/master/examples/set-bucket-notification.js

### PR DESCRIPTION
**Pull request by kannappanr**
MinIO doesn't support `TopicConfig`, but supports `QueueConfig`. Changing the example to use `QueueConfig` instead of `TopicConfig`, which works only on `AWS S3`

Fixes #775

### CODE REVIEW

**Comment by kaankabalak** [comment]
Wouldn't we also need to change the example [on the JavaScript API Reference](https://github.com/minio/minio-js/blob/master/docs/API.md#setBucketNotification) as well?

File: examples/set-bucket-notification.js [hunk 1]
```diff
@@ -21,14 +21,16 @@
...
+  useSSL: false,
   accessKey: 'YOUR-ACCESSKEYID',
   secretKey: 'YOUR-SECRETACCESSKEY'
 })
 
 var config = new Minio.NotificationConfig()
-var arn = Minio.buildARN('aws', 'sns', 'us-east-1', 111112222233, 'topicresource')
-var topic = new Minio.TopicConfig(arn)
+var arn = Minio.buildARN('minio', 'sqs', '', 1, 'webhook')
+var topic = new Minio.QueueConfig(arn)
```
Comment (poornas) [inline examples/set-bucket-notification.js]: @kannappanr , pls change the var topic -> queue here in the example

Comment (kannappanr) [reply examples/set-bucket-notification.js]: done

**Comment by kannappanr** [comment]
> Wouldn't we also need to change the example [on the JavaScript API Reference](https://github.com/minio/minio-js/blob/master/docs/API.md#setBucketNotification) as well?

Done
