### PR TITLE
 Make fPutObject automatically detect content-type

### LINKED ISSUE #763: `fPutObject` does not detect content-type automatically
https://github.com/minio/minio-js/blob/master/examples/fput-object.js#L38-L46

`fPutObject` should detect  content-type automatically, but after https://github.com/minio/minio-js/pull/698 , it doesn't work.

### PR DESCRIPTION
**Pull request by kaankabalak**
This commit also corrects the fput-object.js example and adds functional
tests to check if this feature is working correctly

Fixes #763

### CODE REVIEW

**Comment by kaankabalak** [comment]
Thanks for the feedback @kannappanr, I have just updated the PR

File: src/main/helpers.js [hunk 1]
```diff
@@ -295,6 +295,25 @@ export function readableStream(data) {
...
+
+// Process metadata to insert appropriate value to `content-type` attribute
+export function insertContentType(metaData, filePath) {
+  // first convert case sensitive `content-type` attributes to lowercase
+  var newMetadata = Object.assign({}, metaData)
+  // check if content-type attribute present in metadata
+  var found = false
+  for (var key in newMetadata) {
+    if (key.toLowerCase() === 'content-type') {
+      found = true
```
Comment (kannappanr) [inline src/main/helpers.js]: You can break once you have set it to true.

Comment (kaankabalak) [reply src/main/helpers.js]: Thanks @kannappanr, I just applied the change.

File: src/test/functional/functional-tests.js [hunk 2]
```diff
@@ -255,6 +255,53 @@ describe('functional tests', function() {
...
+      fs.writeFileSync(tmpFileUploadWithExt, _100kb)
+      client.fPutObject(bucketName, _100kbObjectName, tmpFileUploadWithExt, metaData, done)
+    })
+
+    step(`statObject(bucketName, objectName, cb)_bucketName:${bucketName}, objectName:${_100kbObjectName}_`, done => {
+      client.statObject(bucketName, _100kbObjectName, (e, stat) => {
+        if (e) return done(e)
+        // As metadata is provided, even though we have an extension,
+        // the `content-type` should be equal what was declared on the metadata
+        if (stat.metaData && stat.metaData['content-type'] !== 'text/html') {
```
Comment (kannappanr) [inline src/test/functional/functional-tests.js]: Why is it `'text/html'` here and `'text/plain` in the next test?

Comment (kaankabalak) [reply src/test/functional/functional-tests.js]: It is `'text/html'` here as that was the `content-type` specified in the `metaData` on line 98, and it is `'text/plain'` on the next test as we didn't provide any metaData when we uploaded the object and we need to automatically detect the content type from the `.txt` extension.

Comment (kannappanr) [reply src/test/functional/functional-tests.js]: Thanks, did not see that.

File: src/main/helpers.js [hunk 3]
```diff
@@ -295,6 +295,26 @@ export function readableStream(data) {
   s.push(null)
   return s
 }
+
+// Process metadata to insert appropriate value to `content-type` attribute
+export function insertContentType(metaData, filePath) {
+  // first convert case sensitive `content-type` attributes to lowercase
```
[the remark this answers is not in the document]
Comment (kaankabalak) [reply src/main/helpers.js]: Thanks for the feedback, seems like I have overlooked this, will replace this with the appropriate comment

File: src/main/helpers.js [hunk 4]
```diff
@@ -295,6 +295,26 @@ export function readableStream(data) {
...
+  var newMetadata = Object.assign({}, metaData)
```
[the remark this answers is not in the document]
Comment (kaankabalak) [reply src/main/helpers.js]: Yes, I'll replace the usage of `newMetadata` with `metaData`, we can also open an issue if other usages of `newMetadata` are unnecessary on helpers.js

File: src/main/helpers.js [hunk 5]
```diff
@@ -295,6 +295,26 @@ export function readableStream(data) {
...
+  // check if content-type attribute present in metadata
+  var found = false
+  for (var key in newMetadata) {
+    if (key.toLowerCase() === 'content-type') {
+      found = true
+      break
```
[the remark this answers is not in the document]
Comment (kaankabalak) [reply src/main/helpers.js]: Upon further review we saw that we would need to change the case when the metadata is not present as follows:

```
// if `content-type` attribute is not present in metadata,
// then infer it from the extension in filePath
metaData['content-type'] = probeContentType(filePath)
return metaData
```

**Comment by kaankabalak** [comment]
@kannappanr @ebozduman I have sent a commit incorporating the feedback, I would appreciate if you could take another look
