### PR TITLE
fix: enclose ipv6 host with brackets on client request

### LINKED ISSUE #1241: Host Header is set incorrectly for ipv6 addresses with custom port
Specifiying an ipv6 address as an endpoint with a non-default port in the MinioClient constructor, similar to the snippet seen below, will result in an `S3Error: Invalid Request (address 2606:4700::6810:1922:9000: too many colons in address)` Error every time the Object Storage is accessed (e.g. when trying to upload a file).

```js
new Minio.Client({
            endPoint: '2606:4700::6810:1922',
            port: 9000,
            useSSL: false,
            accessKey: useRuntimeConfig().minioKey,
            secretKey: useRuntimeConfig().minioSecret,
 })
```

It seems like the problem is caused by this line: https://github.com/minio/minio-js/blob/796d0d6e57475edbd4a1c18c8bf314c1e285311f/src/internal/client.ts#L420

Which is not taking into account that an ipv6 address should be enclosed in square brackets and sets the host-header to `2606:4700::6810:1922:9000`, probably leading to the port being read as part of the ipv6 address later, resulting in a rejection of the request.
Enclosing the endpoint in the Client constructor with square brackets will throw an `InvalidEndpointError`.

I would expect ipv6 addresses in the host header to be handled in a similar way as it is done by nodejs internally (when no host-header is specified):
(https://github.com/nodejs/node/blob/59ebf6d397c9c468e5beb75b9ed8c82ab0603e3b/lib/_http_client.js#L290-L307)

```js
    if (host && !this.getHeader('host') && setHost) {
      let hostHeader = host;

      // For the Host header, ensure that IPv6 addresses are enclosed
      // in square brackets, as defined by URI formatting
      // https://tools.ietf.org/html/rfc3986#section-3.2.2
      const posColon = StringPrototypeIndexOf(hostHeader, ':');
      if (posColon !== -1 &&
          StringPrototypeIncludes(hostHeader, ':', posColon + 1) &&
          StringPrototypeCharCodeAt(hostHeader, 0) !== 91/* '[' */) {
        hostHeader = `[${hostHeader}]`;
      }

      if (port && +port !== defaultPort) {
        hostHeader += ':' + port;
      }
      this.setHeader('Host', hostHeader);
    }
```

We worked around this problem by having a domain point to our ipv6-only cloud server and using that for the endpoint option.

### PR DESCRIPTION
**Pull request by aldy505**
Closes #1241

### CODE REVIEW

**Comment by trim21** [comment]
can't we just check `:` like standard library does?

**Comment by aldy505** [comment]
> can't we just check `:` like standard library does?

I don't think that makes that much of a difference.

See this sample code:
```js
const net = require("net");

const input = ["localhost", "postgres.arpa", "172.16.0.1", "valid-domain.com", "2001:0db8:85a3:0000:0000:8a2e:0370:7334", "::1234:5678", "::", "::1234:5678:91.123.4.56", "::11.22.33.44"];

for (const i of input) {
  console.log(`Input: ${i}; IsIP? ${net.isIP(i)};`);
}

// Output:
// Input: localhost; IsIP? 0;
// Input: postgres.arpa; IsIP? 0;
// Input: 172.16.0.1; IsIP? 4;
// Input: valid-domain.com; IsIP? 0;
// Input: 2001:0db8:85a3:0000:0000:8a2e:0370:7334; IsIP? 6;
// Input: ::1234:5678; IsIP? 6;
// Input: ::; IsIP? 6;
// Input: ::1234:5678:91.123.4.56; IsIP? 6;
// Input: ::11.22.33.44; IsIP? 6;
```

**Comment by trim21** [comment]
> > can't we just check `:` like standard library does?
> 
> I don't think that makes that much of a difference.
> 
> See this sample code:
> 
> ```js
> const net = require("net");
> 
> const input = ["localhost", "postgres.arpa", "172.16.0.1", "valid-domain.com", "2001:0db8:85a3:0000:0000:8a2e:0370:7334", "::1234:5678", "::", "::1234:5678:91.123.4.56", "::11.22.33.44"];
> 
> for (const i of input) {
>   console.log(`Input: ${i}; IsIP? ${net.isIP(i)};`);
> }
> 
> // Output:
> // Input: localhost; IsIP? 0;
> // Input: postgres.arpa; IsIP? 0;
> // Input: 172.16.0.1; IsIP? 4;
> // Input: valid-domain.com; IsIP? 0;
> // Input: 2001:0db8:85a3:0000:0000:8a2e:0370:7334; IsIP? 6;
> // Input: ::1234:5678; IsIP? 6;
> // Input: ::; IsIP? 6;
> // Input: ::1234:5678:91.123.4.56; IsIP? 6;
> // Input: ::11.22.33.44; IsIP? 6;
> ```

some downstream users are using this package in web environment, using `node:net` may need more polyfill.

**Comment by aldy505** [comment]
> > > can't we just check `:` like standard library does?
> 
> > 
> 
> > I don't think that makes that much of a difference.
> 
> > 
> 
> > See this sample code:
> 
> > 
> 
> > ```js
> 
> > const net = require("net");
> 
> > 
> 
> > const input = ["localhost", "postgres.arpa", "172.16.0.1", "valid-domain.com", "2001:0db8:85a3:0000:0000:8a2e:0370:7334", "::1234:5678", "::", "::1234:5678:91.123.4.56", "::11.22.33.44"];
> 
> > 
> 
> > for (const i of input) {
> 
> >   console.log(`Input: ${i}; IsIP? ${net.isIP(i)};`);
> 
> > }
> 
> > 
> 
> > // Output:
> 
> > // Input: localhost; IsIP? 0;
> 
> > // Input: postgres.arpa; IsIP? 0;
> 
> > // Input: 172.16.0.1; IsIP? 4;
> 
> > // Input: valid-domain.com; IsIP? 0;
> 
> > // Input: 2001:0db8:85a3:0000:0000:8a2e:0370:7334; IsIP? 6;
> 
> > // Input: ::1234:5678; IsIP? 6;
> 
> > // Input: ::; IsIP? 6;
> 
> > // Input: ::1234:5678:91.123.4.56; IsIP? 6;
> 
> > // Input: ::11.22.33.44; IsIP? 6;
> 
> > ```
> 
> 
> 
> some downstream users are using this package in web environment, using `node:net` may need more polyfill.

I feel like I'm missing something here. What about all those `node:http` and `node:https` imports? 

Another side note: We should make this clear on README for what environment we support.

**Comment by trim21** [comment]
> 
> I feel like I'm missing something here. What about all those `node:http` and `node:https` imports?
> 
> Another side note: We should make this clear on README for what environment we support.

there are some issues about this:

https://github.com/minio/minio-js/issues/1002
https://github.com/minio/minio-js/issues/1053

**Comment by aldy505** [comment]
> > I feel like I'm missing something here. What about all those `node:http` and `node:https` imports?
> 
> there are some issues about this:
> 
> #1002 #1053
> 
> > Another side note: We should make this clear on README for what environment we support.
> 
> plus 1 for this

Okay, will implement that tomorrow (or next weekend)

**Comment by aldy505** [comment]
Request for review @trim21 @prakashsvmx

**Comment by prakashsvmx** [comment]
Adding some unit test would be beneficial @aldy505

**Comment by aldy505** [comment]
> Adding some unit test would be beneficial @aldy505

Done

**Comment by trim21** [comment]
Lgtm

**Comment by prakashsvmx** [comment]
Thank you @aldy505  for the contribution.

File: src/internal/join-host-port.ts [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * @internal
+ */
+export function joinHostPort(host: string, port?: number): string {
+  if (port === undefined) {
+    return host
+  }
+
+  // We assume that host is a literal IPv6 address if host has
+  // colons.
+  if (host.includes(':')) {
```
Comment (harshavardhana) [inline src/internal/join-host-port.ts:18]: While this may be sufficient but it is kludgy and can be faked easily. My suggestion is look for the total octets and parse it properly.

https://github.com/TritonDataCenter/node-ip6addr

**Review by harshavardhana — CHANGES_REQUESTED** [review]

File: src/internal/join-host-port.ts (hunk 1 above)
Comment (aldy505) [reply src/internal/join-host-port.ts:18]: I don't think that parsing real IPv6 address is needed. On my implementation, I just ported Go's `net.JoinHostPort` function (code here https://cs.opensource.google/go/go/+/go1.21.4:src/net/ipsock.go;l=235). I think that is sufficient enough.

Comment (harshavardhana) [reply src/internal/join-host-port.ts:18]: Okay lets live with it for now.

**Review by harshavardhana — APPROVED** [review]
