### PR TITLE
Fix Hashing bug and remove putobject string and list 1001 objects tests

### LINKED ISSUE #627: Removing putobject string buffer test and fixing hash calculation bug
Removing putobject string buffer test from functional test as it is incorrect. There are chances that some unicode character can come into play and the test might occasionally fail. 
Fixing Hash calculation bug in getpartialobject test, where the object was of size 6MB and the buffer obtained was 100KB. Failures were seen in Mint when data was read from the file, instead of a fixed data.

### PR DESCRIPTION
**Pull request by kannappanr**
Removing putobject string buffer test as it is incorrect.
There are chances that some unicode character can come into
play and the test might occasionally fail.

Fixed a Hash calculation bug in getpartialobject test, seen in Mint.
The code assumed that the first 100KB of data in the 6MB object will
have the same size as a 100KB object itself.

The listobjects test to list 1001 objects fails intermittently in removeObject part of the test
in Appveyor. Created issue https://github.com/minio/minio-js/issues/629 for tracking purpose.

Fixes #627 and #629

### CODE REVIEW

**Comment by harshavardhana** [comment]
@kannappanr appveyor failed with TIMEOUT. Looks like we have a race of sort.  Triggering a rebuild.
```
  2 failing
  1) functional tests listObjects removeObject(bucketName, objectName, callback)__Remove 1001 objects:
     Error: connect ETIMEDOUT 147.75.201.93:9000
      at Object.exports._errnoException (util.js:907:11)
      at exports._exceptionWithHostPort (util.js:930:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
  2) functional tests "after all" hook:
     S3Error: The bucket you tried to delete is not empty
      at Object.parseError (C:\projects\minio-js\dist\main\xml-parsers.js:56:11)
      at C:\projects\minio-js\dist\main\transformers.js:117:22
      at DestroyableTransform._flush (C:\projects\minio-js\dist\main\transformers.js:48:26)
      at DestroyableTransform.<anonymous> (C:\projects\minio-js\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:135:12)
      at finishMaybe (C:\projects\minio-js\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:371:12)
      at endWritable (C:\projects\minio-js\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:378:3)
      at DestroyableTransform.Writable.end (C:\projects\minio-js\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:356:5)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.8.4
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! minio@3.2.0 prepublish: `gulp test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the minio@3.2.0 prepublish script 'gulp test'.
npm ERR! This is most likely a problem with the minio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs minio
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls minio
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\minio-js\npm-debug.log
```

File: src/test/functional/functional-tests.js [hunk 1]
```diff
@@ -1005,12 +987,12 @@ describe('functional tests', function() {
...
-        10,
-        (objectName, cb) => client.removeObject(bucketName, objectName, cb),
-        done
-      )
+      for(var i = 0; i < listObjectsNum; i++) {
+        client.removeObject(bucketName, listPrefixArray[i], function(e) {
+          if (e) return done(e)
+        })
+      }
+      done()
```
Comment (krishnasrinivas) [inline src/test/functional/functional-tests.js]: this is not correct @kannappanr note that in JS things are async
i.e done() gets called even before any of the objects get removed

Comment (kannappanr) [reply src/test/functional/functional-tests.js]: Reverted the changes with the parallel limit set to 5.
